# Generated by Django 3.0.6 on 2020-06-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('patients_name', models.CharField(max_length=100)),
                ('patients_mobile', models.CharField(max_length=15)),
                ('patients_age', models.CharField(max_length=10)),
                ('Right_eye', models.CharField(max_length=50)),
                ('Left_eye', models.CharField(max_length=50)),
                ('frame', models.CharField(max_length=50)),
                ('lenses', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
